import { getTableConfig } from 'drizzle-orm/sqlite-core';

import {
  bodyMetric,
  exercise,
  nutritionEntry,
  userProfile,
  workoutSession,
  workoutSet,
} from './schema';

// expo-sqlite is a native module and cannot be opened in the jest-expo
// environment, so we cannot run migrations against a real :memory: db here.
// These tests verify the schema *definition* — that every table, column,
// index, and FK we expect exists with the right shape. The actual migration
// SQL is generated by drizzle-kit and executed at app boot via useMigrations.
describe('db schema', () => {
  it('defines all 6 tables', () => {
    expect(getTableConfig(userProfile).name).toBe('user_profile');
    expect(getTableConfig(exercise).name).toBe('exercise');
    expect(getTableConfig(workoutSession).name).toBe('workout_session');
    expect(getTableConfig(workoutSet).name).toBe('workout_set');
    expect(getTableConfig(bodyMetric).name).toBe('body_metric');
    expect(getTableConfig(nutritionEntry).name).toBe('nutrition_entry');
  });

  it('body_metric has nullable weight/waist/body_fat', () => {
    const cols = Object.fromEntries(
      getTableConfig(bodyMetric).columns.map(c => [c.name, c]),
    );
    expect(cols.weight.notNull).toBe(false);
    expect(cols.waist.notNull).toBe(false);
    expect(cols.body_fat.notNull).toBe(false);
    expect(cols.date.notNull).toBe(true);
  });

  it('workout_set has cascade-delete FK to workout_session', () => {
    const fks = getTableConfig(workoutSet).foreignKeys;
    const cascadeFk = fks.find(fk => fk.onDelete === 'cascade');
    expect(cascadeFk).toBeDefined();
    expect(getTableConfig(cascadeFk!.reference().foreignTable).name).toBe(
      'workout_session',
    );
  });

  it('user_profile preferred_units defaults to metric', () => {
    const cols = Object.fromEntries(
      getTableConfig(userProfile).columns.map(c => [c.name, c]),
    );
    expect(cols.preferred_units.default).toBe('metric');
    expect(cols.preferred_units.notNull).toBe(true);
  });

  it('expected indexes are declared', () => {
    const indexNames = (table: any) =>
      getTableConfig(table).indexes.map(i => i.config.name);
    expect(indexNames(workoutSession)).toContain('idx_workout_session_date');
    expect(indexNames(bodyMetric)).toContain('idx_body_metric_date');
    expect(indexNames(nutritionEntry)).toContain('idx_nutrition_entry_date');
    expect(indexNames(workoutSet)).toEqual(
      expect.arrayContaining([
        'idx_workout_set_exercise_session',
        'idx_workout_set_session',
      ]),
    );
  });
});
